repos:
  - repo: local
    hooks:
      - id: meta-lint-commit
        name: Lint commit messages
        entry: ./scripts/lint-commit.sh
        language: script
        stages: [ commit-msg ]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      additional_dependencies: ['types-requests']